version: "3"
services:

  jenkins:
    image: jenkinsci/jenkins
    ports:
      - "8080:8080"
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
        # - /var/run/docker.sock:/var/run/docker.sock
        # - /usr/local/bin/docker:/usr/bin/docker 
